// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNYGmVBF_HBVObr5w0j3yCmd3V_0lI60Y',
    appId: '1:685078638401:web:9bf53c057f48a4ac887bc0',
    messagingSenderId: '685078638401',
    projectId: 'safebite-28152',
    authDomain: 'safebite-28152.firebaseapp.com',
    storageBucket: 'safebite-28152.firebasestorage.app',
    measurementId: 'G-D3KYLLGS10',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsy3GJWeuqjBD_Q62-5p5TB1CzjGslTi0',
    appId: '1:685078638401:android:f242068825e6502a887bc0',
    messagingSenderId: '685078638401',
    projectId: 'safebite-28152',
    storageBucket: 'safebite-28152.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD53xZ3MvdNAOi0QDVkCs86zc3V5VcafmI',
    appId: '1:685078638401:ios:c16e1a6b95e25974887bc0',
    messagingSenderId: '685078638401',
    projectId: 'safebite-28152',
    storageBucket: 'safebite-28152.firebasestorage.app',
    iosBundleId: 'com.example.safebite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD53xZ3MvdNAOi0QDVkCs86zc3V5VcafmI',
    appId: '1:685078638401:ios:c16e1a6b95e25974887bc0',
    messagingSenderId: '685078638401',
    projectId: 'safebite-28152',
    storageBucket: 'safebite-28152.firebasestorage.app',
    iosBundleId: 'com.example.safebite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNYGmVBF_HBVObr5w0j3yCmd3V_0lI60Y',
    appId: '1:685078638401:web:1018f6500f1028e3887bc0',
    messagingSenderId: '685078638401',
    projectId: 'safebite-28152',
    authDomain: 'safebite-28152.firebaseapp.com',
    storageBucket: 'safebite-28152.firebasestorage.app',
    measurementId: 'G-RJGE2LFLD9',
  );
}
